version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: iot_database
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  iot-api:
    build:
      context: .
    container_name: iot_api_container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=iot_database;User=iot_user;Password=your_password;"

volumes:
  mysql_data:
